---
deployment:
  tasks:
    - export DEPLOYPATH=/home/n1473180/public_html/
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp jsconfig.json $DEPLOYPATH
    - /bin/cp now.json $DEPLOYPATH
    - /bin/cp nuxt.config.js $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp vercel.json $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R components $DEPLOYPATH
    - /bin/cp -R layouts $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R store $DEPLOYPATH
